### ISSUE TITLE
Architecture revamp to optimize gas costs on the service

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/ethereum-alarm-clock#119]
We've gotten a nice optimization boost from using the delegatecall clone contracts but the current cost of 1 million gas per transaction is still too high. The next steps forward for a _Version 2_ of the Alarm Clock probably requires some significant architectural work especially if it will scale. @kosecki123 and I have been discussing together possible paths forward. Since we are still at the early brainstorming phases of this work, it's much better than we open and discuss this issue here.

Possible solutions

1) Transitioning to an event-only architecture. Instead of storing all the variables in a contract we devise a scheme where we store as much as possible using event logs. The idea here is that we reduce the amount of `SSTORE` we perform when deploying new transaction requests.

2) Use state channels. Instead of deploying each transaction request to the chain, is it possible to deploy it on a state channel? The TimeNodes would then watch this state channel and execute/claim there and commit the final state to the main chain. Possible ideas are committing a merkle root of the transaction requests to the main chain and integrating the necessaries consensus measures into the clients. 

3) Use a plasma chain. I can't speak to what the functional differences between this and state channels would be, but it may be an idea worth exploring.

Please post any discussion here and suggest new ideas. These three are by no means the only possible paths forward here, nor should they be considered the best ones yet.

**Comment by pipermerriam** [comment]
I think option 1 looks very promising.  This could reduce the storage needs for a transaction request to only need to store at very minimum `keccak(all_transaction_params)` and the event to log a large-ish `bytes` value with all of the params in some *known* format.  The client could then reconstruct all of the parameters, pass them to the scheduled request contract which would then be able to verify all of the parameters against it's stored hash.

Another place with expensive gas needs is the `RequestTracker`.  It costs about 250,000 gas if I recall correctly to insert a value into the tracker.  If tracking were done client-side and the tracker merely kept an enumerable array of un-ordered transactions requests, then the client could with some reasonably small overhead, deal with ordering client-side.

**Comment by kosecki123** [comment]
Regarding the `RequestTracker`. 
We could try to replace it with events. In order to handle lack of query possibility over events we could add extra parameter that would refer to time bucket (and block range). 
Every time new scheduled tx is added we'd emit an event that contains additional `indexed unit256 bucket` parameter for e.g given timestamp `1521410400 ` and `900`s (15min) bucket the `bucket`parameter is `1690456`. The size of the time bucket to be defined.

Client side it would be easy and efficient to scan and subscribe to events that shall happen during given time bucket.

The drawback by removing `RequestTracker` is losing the ability to get ordered tx from other smart contracts. @pipermerriam was it the original idea behind it?

**Comment by pipermerriam** [comment]
No, original idea was to handle total ordering, but in hindsite, that doesn't really belong on-chain.  My recommendation would be to not fully remove `RequestTracker`, but update it to just log events rather than actually using `Grove` to index and order the events.

**Comment by lsaether** [comment]
Archiving
