### ISSUE TITLE
Consider claim deposit to be pegged to bounty

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/ethereum-alarm-clock#131]
Currently `deposit` is an optional field that adds confusion for users that want to schedule. Claiming deposits improves the crypto-economics and thus shall be enabled by default.

First proposal is to make it 1:1 with bounty, enforced by the protocol.

**Comment by kosecki123** [comment]
@pipermerriam any thoughts on that? I also consider to soft enable that in at the client side.

**Comment by pipermerriam** [comment]
@kosecki123 I think you can solve this client-side.  Pegging it at the protocol level eliminates the *option* for using changes to the claim deposit size to influence how your call is handled.

Suppose someone is having their scheduled transactions DOS'd by malicious executors who are willing to burn their claim deposits in order to delay execution till after the claim window (and maybe even reclaim their deposit by executing with an alternate client).  Being able to crank up the deposit size increases the cost of this style of attack.

Similarly, I may add a large bounty to the transaction, but the claim bounty doesn't necessarily need to be as large.  If we assume a situation where the network is congested, executors may decline to claim transactions with high claim deposit sizes for fear that their executing transactions won't get accepted during the exclusive execution window.

I'd just *hide* the claim deposit controls from the user either under an *advanced* section, or with a layer of UX (like gas price) which abstracts the number away into a slider with easy to understand labels.

**Comment by lsaether** [comment]
Archiving
